feat(message): show label on message flow
bpmn-io/bpmn-js pull request #1438
Opened 2021-04-26 14:10 UTC by marstamm

Shows the label for referenced messages on message flows

![image](https://user-images.githubusercontent.com/21984219/116094970-465abb80-a6a8-11eb-847b-ffb278d859f8.png)

We decided to focus on rendering the label and not make the label movable/editable at this point. The Message ref can only be added with external tools, so displaying the name is enough for now.

closes #777

2021-04-26 15:31 UTC, barmac commented
Message name is not updated until I resize/move the Message Flow. However, if implementing this would mean a lot of additional work, I am OK with the current implementation.

https://user-images.githubusercontent.com/28307541/116109391-00f0bb00-a6b5-11eb-8064-2438feaabe81.mov

2021-04-27 07:34 UTC, philippfromme commented
Maybe we can achieve that. [`UpdateModdlePropertiesHandler`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/cmd/UpdateModdlePropertiesHandler.js) was built for that purpose and could be adjusted. Not sure though, if we actually use that handler in the properties panel.

2021-04-29 07:42 UTC, philippfromme requested changes
A couple of remarks regarding code style.

2021-04-29 07:42 UTC, philippfromme commented on lib/draw/BpmnRenderer.js
> +        var messageBB = message.getBBox(),
Again, let's rename __BB_ to _Bounds_.

2021-04-29 07:42 UTC, philippfromme commented on lib/draw/BpmnRenderer.js
> +        var translateX = midPoint.x - labelBB.width/2,
Again, spacing before and after every operator.

2021-04-29 08:39 UTC, marstamm commented
Fixed :+1:

2021-04-29 12:09 UTC, nikku commented
Build likely failing due to https://github.com/bpmn-io/diagram-js/pull/543#issuecomment-829146530.

I've re-triggered the actions.

2021-04-29 12:31 UTC, philippfromme approved these changes
Good job. 👏🏻 

Follow-up issue: https://github.com/camunda/camunda-modeler/issues/2234

2021-04-29 12:31 UTC, merged