fix(paste): don't insert multiple shapes on flow
bpmn-io/bpmn-js pull request #1442
Opened 2021-05-03 09:00 UTC by marstamm

![recording](https://user-images.githubusercontent.com/21984219/116857335-e6f73100-abfc-11eb-873c-b7dbbaa19e19.gif)

The UX when dropping on a flow is not ideal, as it gets highlighted when hovering and then disappearing. However, this behavior is consistent with dragging complex elements on a flow.

closes #1440

2021-05-03 14:15 UTC, barmac requested changes
There is no indicator that the operation is disallowed which leads to bad UX in my opinion. I think we should use rules here just how we do in case of moving multiple shapes. See how cursor changes in the attached capture:

https://user-images.githubusercontent.com/28307541/116887291-70712800-ac2a-11eb-842d-9d87ef31feb7.mp4

So instead of removing the `context.elements`, I'd suggest to change code in [`BpmnRules`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/rules/BpmnRules.js#L113).

I will be happy to support you if you have questions.

2021-05-04 07:22 UTC, marstamm commented
Thank you for the hint @barmac, I was not aware we also had this behavior in the bpmnRules. I expended the create Rules:

![recording](https://user-images.githubusercontent.com/21984219/116969063-ed95af00-acb5-11eb-87ad-5bb59ff314d1.gif)
(interestingly, the recorded cursor does not match the one I see, but is still a 'forbidden' one)

2021-05-04 14:03 UTC, barmac approved these changes

2021-05-04 14:03 UTC, merged

2021-05-04 14:04 UTC, barmac commented
It works as expected. Great job!