Update/Remove Embedded Label Bounds on Shape Moved/Resized
bpmn-io/bpmn-js pull request #1586
Opened 2022-01-26 14:11 UTC by Skaiir

Direct issue is #1537
https://github.com/camunda/camunda-modeler/issues/2566
https://github.com/camunda/camunda-modeler/issues/2591

Doing a little write-up to get some ideas and feedback from people here. Note, this is a draft and is not trying to satisfy our definition of done yet. I'm mostly looking for input on implementation here.

## The core problem:

Because we position embedded labels either centrally or center-top (as in expanded SubProcesses), we do not store their bounds information in `di`. This is not a problem for us, but causes issues with other vendors who do rely on these bounds for positioning.

Looking at the positioning of a task with such bounds for example, let move it a few grid points down:

Before:

```xml
<bpmndi:BPMNShape id="Activity_0cq51bw_di" bpmnElement="Activity_0cq51bw">
  <dc:Bounds x="160" y="130" width="100" height="80" />
    <bpmndi:BPMNLabel labelStyle="LabelStyle_0_0" color:color="#d38300">
    <dc:Bounds x="346.96" y="225.35" width="109.98" height="50.05" />
  </bpmndi:BPMNLabel>
</bpmndi:BPMNShape>
```

After:

```xml
<bpmndi:BPMNShape id="Activity_0cq51bw_di" bpmnElement="Activity_0cq51bw">
  <dc:Bounds x="160" y="410" width="100" height="80" />
    <bpmndi:BPMNLabel labelStyle="LabelStyle_0_0" color:color="#d38300">
    <dc:Bounds x="346.96" y="225.35" width="109.98" height="50.05" />
  </bpmndi:BPMNLabel>
</bpmndi:BPMNShape>
```

The internal bounds remain untouched. 

This is not a major problem on individual items, but it does become a larger one when align-to-origin is run, as any vendor using explicit bounds will see their labels displaced relative to the tasks and subProcesses. 

So optimally we would want to handle these `explicitly bounded embedded labels`, but only when they are present. As in, we should still be able to work with their implicit counterpart.

## Implementation requirements:

There are three scenarios we need to consider here.

### Displacement of an activity

This is actually a pretty simple change, we can just listen to `shape.move` inside of the `BpmnUpdater` and propagate whatever delta a shape receives to the label bounds (if it has them). This applies to tasks and sub-processes, and is implemented already in the PR. 

### Resizing of a sub-process

This is a little more complicated, as we align things differently based on the `collapsed` flag of the sub-process shape. I added a helper function to calculate the "proper" positioning here. This is attached to the `shape.resize` event in the updater as well, and is somewhat hacky feeling. I'd really be up for suggestions / improvements here. The maths might also be a bit rough. 

### Changing the label itself (help wanted here)

Now this is the major problem here. The embedded label does not have an associated shape, therefore there's no serialized information on its actual bounds accessible. The only place where we actually do calculate the width and height (which are the only things we need here) is at the rendering stage. What this means is that we have no data to work from.

To fix this, there's only two options in my mind, either recalculate the bounds with the textRenderer, which from talks with @philippfromme seems to be an expensive operation, and also duplication. Or, we somehow cache them, but propagating renderer information up to the BpmnUpdater just feels really clunky. This is the main issue here, and the reason for the draft PR. 

## Some other considerations

When morphing sub-processes to tasks, or tasks to other kinds of tasks, we loose the label info entirely. Would we want to extend handling to these cases as well? It does feel weird that morphing a task with a colored label removes the styling (you can try this with the example diagram). 

## Test diagram
[embedded bounded labels.txt](https://github.com/bpmn-io/bpmn-js/files/7942321/embedded.bounded.labels.txt)

2022-01-26 14:33 UTC, marstamm commented
Have we considered removing the bounds completely from embedded labels? Those are valid according to the BPMN spec and how we handle newly created Tasks since #1540 .

2022-01-26 15:55 UTC, MaxTru commented
What about fixing the (rather easy?) case of `shape.move` for now, to resolve the MIWG issue and track the other stuff in a seperate issue. => incremental progress

2022-01-26 16:05 UTC, nikku commented on lib/features/modeling/BpmnUpdater.js
> +    if (hasExplicitlyBoundedEmbeddedLabel(shape)) {
If we hook in prior to the DI update we#ll be able to diff bounds (shape bounds vs. bounds stored in DI).

No need for separate logic to handle shape move (do / undo) as well as resize (do / undo).

2022-01-26 16:05 UTC, nikku commented on lib/features/modeling/BpmnUpdater.js
> +  hasExplicitlyBoundedInternalLabel as hasExplicitlyBoundedEmbeddedLabel
If a utility has no use outside of a single file (which seems to be the case here), leave it inside that single file.

We prevent utility creep this way.

2022-01-26 16:06 UTC, nikku commented on lib/util/LabelUtil.js
> +  return (is(shape, 'bpmn:Task') || is(shape, 'bpmn:SubProcess'))
is('bpmn:Activity')

2022-01-26 16:07 UTC, nikku commented
An interesting approach @marstamm mentioned:If we move/resize/update an element, reset the embedded label (no bounds). Other tool vendors must support it and it is the most simple solution for us. 

It does conflict with our notion to play nicely with others. I'd therefor spend a little bit of time to [consider small improvements to this PR](https://github.com/bpmn-io/bpmn-js/pull/1586#discussion_r792795822) and just make it work for others, out of the box.

2022-02-07 13:41 UTC, Skaiir commented
Okay so after quite a bit of back and fourths. This PR does the following things:

Adjusts internal label bounds when a move operation occurs. 
Clears internal label bounds when a resize operation occurs, I have some magic code in the bank that I git stashed and will put on a personal branch shortly which does do the resize operation, but it might be too much complexity. 

Sets up tests to make sure the two above things operate properly. 

@nikku I decided to keep the move handling because the issue with align-to-origin would reset so many things on other vendors diagrams. I think this is the safest thing to do. 

Related to: https://github.com/camunda/camunda-modeler/issues/2591

Following merge I will update this as well to reflect the current state - https://github.com/bpmn-io/bpmn-js/issues/1537

2022-02-07 14:52 UTC, barmac requested changes
We need to also make sure we don't drop properties beside bounds when a shape is resized.

2022-02-07 14:52 UTC, barmac commented on lib/features/modeling/BpmnUpdater.js
> +      di.label = this._bpmnFactory.createDiLabel();
This means that we also drop the colors, don't we? We should make sure no properties beyond bounds are dropped. Let's have a test case for that. I noticed you already provided a BPMN with labelStyle and color:color -> this is a good example to verify correct behaviour.

2022-02-07 14:52 UTC, barmac commented on lib/features/modeling/BpmnUpdater.js
> +    && getDi(shape).label.bounds != undefined;
I believe it's enough to check if bounds are truthy (they should always be an object):

```suggestion
    && getDi(shape).label.bounds;
```

2022-02-07 14:52 UTC, barmac commented on lib/features/modeling/BpmnUpdater.js
> +    if (shape.width != di.bounds.width || shape.height != di.bounds.height) {
Let's use strict comparison as we don't want to do type conversion:

```suggestion
    if (shape.width !== di.bounds.width || shape.height !== di.bounds.height) {
```

2022-02-08 13:38 UTC, marstamm reviewed
Works as expected. See my two comments below and then I think we can merge it

One thing I noticed is that we replace the label in a replace operation. Pretty sure this is out of scope of this PR
![Recording 2022-02-08 at 14 36 18](https://user-images.githubusercontent.com/21984219/152998060-a5952666-e004-4ace-9dd4-59483346ff20.gif)

2022-02-08 13:38 UTC, marstamm commented on test/spec/features/modeling/ResizeShapeSpec.js
> +    var subProcess = elementRegistry.get('Activity_1'), subProcessDi = getDi(subProcess);
Let's only use one variable assignment per line
```suggestion
    var subProcess = elementRegistry.get('Activity_1'), 
          subProcessDi = getDi(subProcess);
```

2022-02-08 13:38 UTC, marstamm commented on test/spec/features/modeling/MoveShapeSpec.js
> +    var task = elementRegistry.get('Activity_0'), taskDi = getDi(task);
Same here
```suggestion
    var task = elementRegistry.get('Activity_0'), 
          taskDi = getDi(task);
```

2022-02-08 16:06 UTC, Skaiir commented
Yup I was just waiting on the checks to go green :D, now tis done.

2022-02-08 16:13 UTC, philippfromme commented on lib/features/modeling/BpmnUpdater.js
> +  delta,
```suggestion
  delta
```

🤡

2022-02-08 16:33 UTC, philippfromme commented on lib/features/modeling/BpmnUpdater.js
> +      delete di.label.bounds;
This action is __not__ revertable. Once you resize a sub-process undoing that action won't bring the DI bounds back. Are we aware of that?

2022-02-10 08:27 UTC, philippfromme commented
I'm reviewing this now. 🕵🏻

2022-02-10 11:13 UTC, philippfromme approved these changes
I've added a couple of adjustments. Most importantly, I moved the tests to the appropriate files. As a general rule, there's one top-level `describe` per file.

Good job! I'm happy about the solution. 👍🏻

2022-02-10 11:13 UTC, merged