Use ES2018 syntax
bpmn-io/bpmn-js pull request #1737
Opened 2022-09-08 14:36 UTC by barmac

This is a draft which will be adjusted if we decide to go the ES2018 way.

2022-09-13 08:10 UTC, pinussilvestrus commented
Should we integrate https://github.com/bpmn-io/eslint-plugin-bpmn-io/pull/15 already with this PR as well?

2022-09-13 08:15 UTC, barmac commented
I can add this.

2022-09-14 07:24 UTC, barmac commented
> Should we integrate [bpmn-io/eslint-plugin-bpmn-io#15](https://github.com/bpmn-io/eslint-plugin-bpmn-io/pull/15) already with this PR as well?

Done, and I also fixed one ESNext case ^^

2022-09-19 05:49 UTC, nikku commented
Let us unbuild the partial `prototype -> class` migration for the moment as discussed and consider a holistic upgrade (i.e. via [codemod](https://github.com/cpojer/js-codemod/)) at some point.

2022-09-19 05:50 UTC, nikku requested changes
> Let us unbuild the partial prototype -> class migration for the moment as discussed and consider a holistic upgrade (i.e. via [codemod](https://github.com/cpojer/js-codemod/)) at some point.

2022-09-20 07:47 UTC, barmac commented
Modelers & Modeling migrations are now removed since they were mostly about `class`.

2022-09-20 08:07 UTC, barmac commented
Ready for another round.

2022-09-20 09:28 UTC, nikku approved these changes

2022-09-20 09:29 UTC, merged