Add append element
bpmn-io/bpmn-js pull request #1802
Opened 2023-01-11 11:12 UTC by smbea

Closes #1801 
Depends on #1807

**How it looks:**

Uploading Screen Recording 2023-01-12 at 13.46.56.mov…

**Note:**
I used the same approach as for icons as we do in align and distribute. It seems to be the best solution we have for now (maybe the svg updates could be automated in the future)

2023-01-11 18:30 UTC, nikku commented
@smbea Any reason we're not using the `...` icon? As far as I am aware the icon you chose is a web modeler extension, specifically to append a new connector. I'd not want to incorporate it into the core.

If you want to I can dig up earlier discussions on "which icon to choose", where we settled on "...".

2023-01-11 18:31 UTC, nikku commented on lib/features/rules/BpmnRules.js
> +    'bpmn:SequenceFlow' ])) {
Should it include participant, lane, data elements?

2023-01-12 13:40 UTC, philippfromme commented
I found two quirks:

1. You can append elements that can only be connected in the opposite direction
2. You can append elements that cannot be connected at all

![brave_brn6O8ga1Q](https://user-images.githubusercontent.com/7633572/212081427-48a28b3b-7f50-4cc2-bb1b-33acce3f7255.gif)

Are we aware of this?

2023-01-12 15:34 UTC, nikku commented
@smbea Please also double-check existing bugs on the prototype. We want to make sure those don't re-open in the Camunda Modeler.

2023-01-13 07:40 UTC, nikku requested changes

2023-01-13 07:40 UTC, nikku commented on lib/features/context-pad/ContextPadProvider.js
> +import ICONS from './ContextPadIcons';
Feels kinda odd to now spread "icons" across the whole code base.

What about collecting all icons in a shared place? They can be bundled once, as needed, and consumed from anywhere.

I could imagine to provide icons through `lib/icons` to start with.

2023-01-13 07:40 UTC, nikku commented on lib/features/context-pad/ContextPadIcons.js
> +var icons = {
Let's not expose icons as a default export, but through a dedicated export:

```
const append = '...';

export { append };
``` 

This way the file can be tree-shaken (only actual icons used are consumed).

CC @barmac.

2023-01-13 10:36 UTC, nikku commented on lib/features/modeling/ElementFactory.js
> +    businessObject.triggeredByEvent = attrs.triggeredByEvent;
We should also delete `attrs` in this case, cf. handling of other special attributes.

2023-01-13 10:36 UTC, nikku approved these changes

2023-01-13 10:36 UTC, nikku commented on lib/features/modeling/ElementFactory.js
> +    businessObject.triggeredByEvent = attrs.triggeredByEvent;
Also, consider adding a test case for this.

2023-01-13 16:36 UTC, nikku requested changes
Great progress so far :tada:.

Some UX related findings:

* Append should only show prominent items initially (cf. [demo](https://bpmn-io.github.io/bpmn-js-connectors-extension/?aa=1)
  
  ![capture em6aBr_optimized](https://user-images.githubusercontent.com/58601/212370240-67162fd7-ae0b-44bb-9d94-a08b8a446d3a.gif)

* Append should not offer blank `Boundary Event` => it is the same as an intermediate catch event
  
* Append should support _drag out to place anywhere_, (cf. [demo](https://bpmn-io.github.io/bpmn-js-connectors-extension/?aa=1):

  ![capture VWj1WG_optimized](https://user-images.githubusercontent.com/58601/212370764-7aa9cc50-80dd-427f-94fe-b2da95ce4a90.gif)
  
* Append should allow to add boundary events (cf. [demo](https://bpmn-io.github.io/bpmn-js-connectors-extension/?aa=1), but other than in the demo **always attach manually**:
  
  ![capture KTMdrD_optimized](https://user-images.githubusercontent.com/58601/212371437-ea92ef5a-1493-4116-b9fa-589af967f045.gif)

2023-01-16 09:26 UTC, nikku commented
> In the spirit of integrating things incrementally, this can be implemented on top, no?

Yes, of course. Let's just ensure we don't at least evaluate it at some point.

I've added it to the [EPIC](https://github.com/bpmn-io/bpmn-js/issues/1627) just to be sure.

2023-01-18 11:46 UTC, nikku commented on lib/features/popup-menu/AppendMenuProvider.js
> +AppendMenuProvider.prototype.getEntries = function(element) {
Let's use the new version `PopupMenuProvider#getPopupMenuEntries`.

```suggestion
AppendMenuProvider.prototype.getPopupMenuEntries = function(element) {
```

2023-01-18 11:54 UTC, nikku approved these changes
Thanks for this contribution! Very nice:

* Integration with rules
* Improved handling of icons
* Solid test coverage
* Really intuitive modeling

----

To highlight one thing I love how natural this feels to me (auto place vs. manual placement), i.e. considering the "non-interrupting boundary" placement here:

![capture eoOWhe_optimized](https://user-images.githubusercontent.com/58601/213164452-de84423b-bc92-47fd-99c5-898a467b8d4f.gif)

----

If I had one wish then it would be to be less strict regarding when we show the menu. i.e. for link throw events:

![screenshot DZKHtk](https://user-images.githubusercontent.com/58601/213164506-feccec63-a35c-401f-8e06-74f3ebf53998.png)

If we combine "showing it in more places" with https://github.com/bpmn-io/bpmn-js/issues/1621 you could argue that creating a (matching) link catch event (or creating a matching catching event for whatever throw event is selected) could be the primary action provided to a user. :)

Great work overall.

2023-01-18 12:10 UTC, merged