render vertical pools and lanes
bpmn-io/bpmn-js pull request #2024
Opened 2023-11-12 15:52 UTC by sombrek

Hi there,

I propose an implementation for rendering vertical pools and lanes.
Fixes #57 

The labels of vertical pools and lanes as well as the pool label separator are now correctly rendered on top.
Labels of vertical black-box pools are rotated.

The spec implies that horizontal is the default and I adhere to that, i.e. a missing isHorizontal attribute defaults to true.

Could you please provide some information how I can test this?
I thought about adding a vertical version of https://github.com/bpmn-io/bpmn-js/blob/7aee439f47cf0daebcb6131e84f0f9a9d2a51544/test/fixtures/bpmn/draw/pools.bpmn
...but I'm not quite sure if that'll do it.

Kind regards

<details>
<summary>Showcase</summary>
![showcase](https://github.com/bpmn-io/bpmn-js/assets/150448993/8a13f9f4-e2fb-4ac2-a6c1-d156e97ee5ac)
</details>

2023-11-14 12:53 UTC, philippfromme commented
Thank you for your contribution. Why is this a draft? Are you still working on it?

2023-11-16 19:22 UTC, sombrek commented
Thank you for your feedback.

The suggested test has been added nd it passes.
I also adjusted the IsHorizontalFix. However, I believe this affects only modeling, but not rendering.

> `isHorizontal` has no default value

The spec is funny. Pools and lanes shall be horizontal, if either `isVertical` is `false` or missing (BPMN 2.0.2, page 402). However no other mention of `isVertical` appears in the spec, so I thought they changed it but forgot to update that part of the spec.

Anyway, is this the point where I should mark the pull request as ready?

2023-11-28 15:43 UTC, nikku commented on lib/features/modeling/behavior/IsHorizontalFix.js
> +      di.set('isHorizontal', isHorizontal);
Let's add a test case to verify this is being set to the proper thing, on move.

2023-11-28 19:44 UTC, philippfromme commented
Label editing might have to be adjusted. This could be a follow-up.

![brave_igjo7RaiZq](https://github.com/bpmn-io/bpmn-js/assets/7633572/64e1ffd9-b11d-467e-91d3-f228959aa435)

2023-11-30 10:01 UTC, nikku requested changes
@sombrek We'd need to adjust label editing [here](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/label-editing/LabelEditingProvider.js#L279) + add a test case.

2023-11-30 19:32 UTC, sombrek commented
@nikku and @philippfromme Thanks for your support.

I'd like to ask you to reconsider your latest remarks as I feel they extend the scope of this pull request too much.

In this pull request I specifically wanted to target vertical rendering, i.e. issue #57 only.
The issue tracker separately lists issue #507 for vertical modeling. I consider labeling and moving stuff around modeling, so I didn't have a look at that yet. I probably diluted my intent by implementing the changes to `IsHorizontalFix`. Sorry for that.

As suggested earlier, I added test cases that ensure the attribute remains intact after moving.
Are you willing to accept that as a complete increment or do you prefer another approach?

2023-12-01 08:28 UTC, nikku commented
@sombrek Thanks for getting back to us. We believe that supporting a feature end-to-end, especially as the remaining steps are low effort, is valuable.

You're right, you planned to contribute _rendering_. We'll only incorporate rendering once _basic modeling_ works, too.

As I understand you you don't have capacity to work on the modeling part? If that is the case then we're happy to help out. Note that this may take a little bit longer then to get this merged.

2023-12-02 16:31 UTC, sombrek commented
@nikku Labeling now works as expected. Thanks for pointing me to the code.

> Fun fact: Label editing was our first modeling feature, before we could do anything else.

Well, you've got tho give the baby a name.

2023-12-04 10:51 UTC, merged

2024-01-11 14:03 UTC, dymkkk commented
I implemented a demo, but there were some issues with the lane when adjusting the size
[demo](http://test.cn-wbst.cn/dym/bpmn/)

2024-01-11 16:20 UTC, sombrek commented
@dymkkk Thanks for trying.

This issue was only about rendering (drawing) vertical pools lanes.

I'm currently working on resize issues. Those are documented in issue #2062.
There are more issues that I plan to work on after that.
A summary of what's not working yet can be found in issue #507.

2024-01-11 17:23 UTC, dymkkk commented
> @dymkkk Thanks for trying.
> 
> This issue was only about rendering (drawing) vertical pools lanes.
> 
> I'm currently working on resize issues. Those are documented in issue #2062. There are more issues that I plan to work on after that. A summary of what's not working yet can be found in issue #507.

This demo covers more than just that. You probably didn't try to create swim lanes. Swimlanes can already be split and created vertically, and can be resized, but there are some problems with range limitations. I also noticed your plan. If you are continuing to do it, then I still look forward to your results. Thanks