Search improvements
bpmn-io/bpmn-js pull request #2187
Opened 2024-06-03 20:48 UTC by philippfromme

Related to https://github.com/bpmn-io/diagram-js/pull/913

2024-08-21 14:06 UTC, barmac commented
@philippfromme There are conflicts to resolve in this PR

2024-08-21 14:07 UTC, barmac commented on lib/features/search/BpmnSearchProvider.js
> +    return !isLabel(element) && element !== rootElement;
👍 for helper usage

2024-08-21 14:32 UTC, barmac commented
Let's fix the conflict, and it is ready to be merged.

2024-08-21 22:36 UTC, nikku commented
I checked this PR once again, UX wise, as I previously lost one of my reviews :see_no_evil: 

One thing I found is that clicking anywhere on the canvas with search open would reset the viewport to the previous viewbox. I believe if the user clicks anywhere (closing search), then they want to commit the current viewbox, and do not expect it to "jump back". Things are, of course, different if they press `ESC` ("GET ME OUT OF THERE").

Also I found that sometimes focussing of elements is odd (cf. jumping when selecting different sub-processes that would actually be "in view". 

Both visualized in the following recording:


![capture ngU8IG_optimized](https://github.com/user-attachments/assets/b379e36d-5419-4f27-afbe-8618076ef3d9)

2024-08-28 10:31 UTC, nikku requested changes
Cf. https://github.com/bpmn-io/bpmn-js/pull/2187#issuecomment-2303198593.

Let's consider if we want to fix the last bug.

2024-08-28 10:34 UTC, abdul99ahad submitted a review, later dismissed
Merge conflicts in the PR. Please resolve them.

2024-09-12 12:14 UTC, nikku approved these changes
Great stuff.

2024-09-12 12:15 UTC, nikku commented
Updated on top of latest DEV branch + pulled in diagram-js@14.10.0.

2024-09-12 12:23 UTC, merged

2024-09-12 14:36 UTC, nikku commented
Did some integration testing on the [released changes](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#17110), and identified potential follow-ups:

* https://github.com/bpmn-io/bpmn-js/issues/2232
* https://github.com/bpmn-io/bpmn-js/issues/2233